# Suunto OAuth Client Configuration
quarkus.rest-client.suunto-oauth.url=https://cloudapi-oauth.suunto.com

# Suunto API Client Configuration
quarkus.rest-client.suunto-api.url=https://cloudapi.suunto.com

# Suunto Credentials
suunto.client-id=${SUUNTO_CLIENT_ID:tu-client-id}
suunto.client-secret=${SUUNTO_CLIENT_SECRET:tu-client-secret}
suunto.subscription-key=${SUUNTO_SUBSCRIPTION_KEY:tu-subscription-key}

# Initial Refresh Token (Seed)
suunto.initial-refresh-token=${SUUNTO_REFRESH_TOKEN:tu-refresh-token-inicial}