# --- HTTP ---
quarkus.http.port=8080

# --- Datasource (SQLite, fichero local y portable) ---
quarkus.datasource.db-kind=sqlite
quarkus.datasource.jdbc.url=jdbc:sqlite:local.db

# --- Liquibase ---
# La migración corre al arrancar; el fichero local.db se crea si no existe.
quarkus.liquibase.migrate-at-start=true
quarkus.liquibase.change-log=db/changelog/db.changelog-master.yaml
