# Suunto OAuth Client Configuration
quarkus.rest-client.suunto-oauth.url=https://cloudapi-oauth.suunto.com

# Suunto API Client Configuration
quarkus.rest-client.suunto-api.url=https://cloudapi.suunto.com

# Suunto Credentials
suunto.api.authorization=${SUUNTO_API_AUTHORIZATION:dev_auth_token}
suunto.api.subscription-key=${SUUNTO_API_SUBSCRIPTION_KEY:dev_subscription_key}

# Initial Refresh Token (Seed)
suunto.initial-refresh-token=${SUUNTO_REFRESH_TOKEN:tu-refresh-token-inicial}


# PostgreSQL Database Configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=kore_user
quarkus.datasource.password=kore_password
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/kore_db

# Hibernate ORM Configuration
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.mapping.format.global=ignore
quarkus.hibernate-orm.log.sql=false

quarkus.liquibase.migrate-at-start=true

quarkus.liquibase.change-log=db/changelog/db.changelog-master.yaml

