# Suunto OAuth Client
quarkus.rest-client.suunto-oauth.url=https://cloudapi-oauth.suunto.com

# Suunto API Client
quarkus.rest-client.suunto-api.url=https://cloudapi.suunto.com

# Suunto Credentials
suunto.client-id=${SUUNTO_CLIENT_ID}
suunto.client-secret=${SUUNTO_CLIENT_SECRET}
suunto.subscription-key=${SUUNTO_SUBSCRIPTION_KEY}
suunto.initial-refresh-token=${SUUNTO_REFRESH_TOKEN}

# PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=kore_user
quarkus.datasource.password=kore_password
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/kore_db

# Hibernate ORM
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.mapping.format.global=ignore
quarkus.hibernate-orm.log.sql=false

# Liquibase
quarkus.liquibase.migrate-at-start=true
quarkus.liquibase.change-log=db/changelog/db.changelog-master.yaml
